### ISSUE TITLE
CLI: arguments order

### ISSUE THREAD

**Issue by faulknercs** [the-spyke/undercut#20]
Hi, at first thanks for this wonderful package :)

I've found the next issue: I have to specify `-i` or `--import` options at the end of the command otherwise I'm getting the error:

![image](https://user-images.githubusercontent.com/1216573/106515293-844fa580-64e6-11eb-9a0c-ebdecc794750.png)

Documentation says nothing about the order of the arguments.

**Comment by the-spyke** [comment]
Hi, the `import` option is an array (because you may want to import several modules), so if you're passing positional arguments right after it you need to explicitly state this by including double dashes `--` like so:

`undercut -i "path" -- 'map(x => x + 1)'`

I'll add this to documentation, thanks!
